stages:
  prepare_data:
    cmd: python src/data/prepare_data.py data/raw data/interim/interim_df.csv
    deps:
      - data/raw
      - src/data/prepare_data.py
    outs:
      - data/interim/interim_df.csv

  make_dataset:
    cmd: python src/data/make_dataset.py data/interim/interim_df.csv data/processed/dataset.pkl
    deps:
      - data/interim/interim_df.csv
      - src/data/make_dataset.py
    outs:
      - data/processed/dataset.pkl



