[tool.poetry]
name = "kaspersky-test"
version = "0.1.0"
description = ""
authors = ["xrabroff <xrabroff.dmitry@yandex.ru>"]
readme = "README.md"
packages = [{include = "kaspersky_test"}]

[tool.poetry.dependencies]
python = "^3.10"
dvc = "^2.58.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
